version: "3.7"

services:
  fronted:
    build:
      dockerfile: dockerfile.dev
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    environment:
      - WATCHPACK_POLLING=true

  json:
    image: clue/json-server
    ports:
      - 8080:80
    volumes:
      - ./data.json:/data/db.json
