name: CICD

on:
  push:
    branches: [main]

jobs: 
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: first down the docker-compose 
        run: docker-compose -f "docker-compose.dev.yaml" down
      - name: then up the docker-compose
        run: docker-compose -f "docker-compose.dev.yaml" up -d
